### ISSUE TITLE
All day events truncated to one only

### ISSUE THREAD

**Issue by luedi0** [pablojimenezmateo/kindle-wallpaper#21]
Hi Mateo,
I've found a bug. All day events are truncated to one only.
A line to increment the count is missing. Can you give me push commit access again?
I would also add a docker container as server to the project
Best regards, Max

**Comment by pablojimenezmateo** [comment]
Hi luedi0,

I think the easiest way would be for you to fork this repo, add your changes to your fork and, once tested, open a Pull Request.

Are you familiar with this workflow? I can guide you through it if you want :D I really appreciate your additions.
